os:
  - linux
  - osx

language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.3.3
  - 2.4.0
  - jruby-9.1.7.0

matrix:
  exclude:
    # Travis does not provide 1.8.7 on OSX
  - rvm: 1.8.7
    os: osx
    # Rake 11.x does not support Ruby 1.8.7
  - rvm: 1.8.7
    gemfile: testing/gemfiles/rake11.gemfile
    # Rake 12.x does not support Ruby 1.8.7
  - rvm: 1.8.7
    gemfile: testing/gemfiles/rake12.gemfile

gemfile:
  - testing/gemfiles/cuke_modeler0.gemfile
  - testing/gemfiles/cuke_modeler1.gemfile
  - testing/gemfiles/rake10.gemfile
  - testing/gemfiles/rake11.gemfile
  - testing/gemfiles/rake12.gemfile

# todo - Remove this once TravisCI fixes their bundler issue (https://github.com/alphagov/govuk_template/pull/186)
before_install:
  - gem install bundler -v 1.9.10

script: bundle exec rake cuke_cataloger:ci_build
